import type { ProjectGraphApi } from './networkGraph.types'

// Fixture/test data only. Production graph rendering should prefer the backend
// project graph read model and use these rows for unit tests/local examples.
export const projectGraphApiFixture: ProjectGraphApi = {
  project: {
    id: 'project-fixture',
    name: 'Solar panel supply project',
    status: 'ACTIVE',
  },
  visibility: {
    roleCodes: ['ORG_ADMIN'],
    financeNodesIncluded: true,
  },
  nodes: [
    {
      id: 'Organization:org-fixture',
      entityType: 'Organization',
      entityId: 'org-fixture',
      label: 'TechBuild Sdn Bhd',
      subtitle: 'Organization',
      status: 'standalone_sme',
      category: 'organization',
      sourcePath: '/dashboard',
      position: { x: 80, y: 80 },
    },
    {
      id: 'BuyerCustomer:buyer-fixture',
      entityType: 'BuyerCustomer',
      entityId: 'buyer-fixture',
      label: 'SolarTech Industries',
      subtitle: 'Buyer',
      status: 'ACTIVE',
      category: 'party',
      sourcePath: '/dashboard',
      position: { x: 80, y: 260 },
    },
    {
      id: 'Supplier:supplier-fixture',
      entityType: 'Supplier',
      entityId: 'supplier-fixture',
      label: 'Mega Components',
      subtitle: 'Approved supplier',
      status: 'ACTIVE',
      category: 'party',
      sourcePath: '/procurement/suppliers/supplier-fixture',
      position: { x: 820, y: 260 },
    },
    {
      id: 'PurchaseOrder:po-fixture',
      entityType: 'PurchaseOrder',
      entityId: 'po-fixture',
      label: 'PO-2026-0001',
      subtitle: 'Purchase order',
      status: 'ISSUED',
      category: 'procurement',
      sourcePath: '/procurement/purchase-orders/po-fixture',
      position: { x: 580, y: 260 },
    },
    {
      id: 'EvidencePack:pack-fixture',
      entityType: 'EvidencePack',
      entityId: 'pack-fixture',
      label: 'Project evidence pack',
      subtitle: 'Evidence pack',
      status: 'ANCHOR_PENDING',
      category: 'evidence',
      sourcePath: '/evidence/packs/pack-fixture',
      position: { x: 340, y: 400 },
    },
    {
      id: 'ProcurementOpportunity:opp-fixture',
      entityType: 'ProcurementOpportunity',
      entityId: 'opp-fixture',
      label: 'Solar panel working capital',
      subtitle: 'Finance opportunity',
      status: 'READY_FOR_APPLICATION',
      category: 'finance',
      sourcePath: '/finance/opportunities',
      position: { x: 100, y: 520 },
    },
    {
      id: 'MudarabahApplication:app-fixture',
      entityType: 'MudarabahApplication',
      entityId: 'app-fixture',
      label: 'Application app-fixture',
      subtitle: 'MYR 125000',
      status: 'DUE_DILIGENCE_IN_REVIEW',
      category: 'finance',
      sourcePath: '/finance/applications/app-fixture/overview',
      position: { x: 340, y: 580 },
    },
  ],
  edges: [
    {
      id: 'buyer:buys_from:supplier',
      sourceNodeId: 'BuyerCustomer:buyer-fixture',
      targetNodeId: 'Supplier:supplier-fixture',
      label: 'buys from',
    },
    {
      id: 'supplier:supplies:po',
      sourceNodeId: 'Supplier:supplier-fixture',
      targetNodeId: 'PurchaseOrder:po-fixture',
      label: 'supplies',
    },
    {
      id: 'pack:evidences:po',
      sourceNodeId: 'EvidencePack:pack-fixture',
      targetNodeId: 'PurchaseOrder:po-fixture',
      label: 'evidences',
    },
    {
      id: 'opp:funds:po',
      sourceNodeId: 'ProcurementOpportunity:opp-fixture',
      targetNodeId: 'PurchaseOrder:po-fixture',
      label: 'funds',
    },
    {
      id: 'opp:approves:app',
      sourceNodeId: 'ProcurementOpportunity:opp-fixture',
      targetNodeId: 'MudarabahApplication:app-fixture',
      label: 'approves',
    },
  ],
}
