import type { DashboardContent } from './dashboard.types'

const sharedSignals = [
  {
    id: 'fabric-pending',
    label: 'Fabric anchors',
    value: '3 pending',
    description:
      'Anchor requests are queued locally. Do not mark anchors verified until verification returns a transaction reference.',
    severity: 'warning',
    targetRoute: '/integrations',
  },
  {
    id: 'outbox-failed',
    label: 'Outbox retries',
    value: 2,
    description:
      'External integration requests have failed and need retry or reconciliation review.',
    severity: 'danger',
    targetRoute: '/integrations',
  },
  {
    id: 'audit-recent',
    label: 'Recent audit events',
    value: 18,
    description:
      'Recent material actions are available for review in the audit timeline.',
    severity: 'neutral',
    targetRoute: '/audit/search',
  },
] as const

const sharedActivities = [
  {
    id: 'act-evidence-gap',
    title: 'Evidence checklist updated',
    description: 'APP-2026-001 still has two unresolved evidence items.',
    eventType: 'EVIDENCE_CHECKLIST_ITEM_COMPLETED',
    occurredAt: '2026-06-02T10:15:00.000Z',
    targetRoute: '/finance/applications',
  },
  {
    id: 'act-anchor-requested',
    title: 'Anchor request queued',
    description: 'Purchase order hash is waiting for mock Fabric worker processing.',
    eventType: 'FABRIC_ANCHOR_REQUESTED',
    occurredAt: '2026-06-02T09:42:00.000Z',
    targetRoute: '/integrations',
  },
  {
    id: 'act-audit-search',
    title: 'Audit search refreshed',
    description: 'Auditable procurement and finance events are visible for reviewers.',
    eventType: 'AUDIT_EVENTS_QUERIED',
    occurredAt: '2026-06-01T16:20:00.000Z',
    targetRoute: '/audit/search',
  },
] as const

export const dashboardFixtures: Record<DashboardContent['role'], DashboardContent> = {
  sme_admin: {
    role: 'sme_admin',
    title: 'Organization cockpit',
    subtitle:
      'Setup readiness, user access, integration health, and audit-sensitive node operations.',
    kpis: [
      {
        id: 'active-users',
        label: 'Active users',
        value: 14,
        helper: '3 invitations still need follow-up',
        trend: 'up',
        severity: 'neutral',
      },
      {
        id: 'setup-complete',
        label: 'Setup completeness',
        value: '72%',
        helper: 'Backup and OIDC setup remain incomplete',
        trend: 'flat',
        severity: 'warning',
      },
      {
        id: 'access-review',
        label: 'Access review',
        value: 'Due',
        helper: 'Monthly role review is open',
        severity: 'warning',
      },
      {
        id: 'audit-events',
        label: 'Audit events',
        value: 1247,
        helper: 'Append-only local audit trail',
        trend: 'up',
        severity: 'success',
      },
    ],
    tasks: [
      {
        id: 'admin-review-users',
        title: 'Review pending invitations',
        description: 'Three invited users have not accepted organization access.',
        targetRoute: '/admin/users',
        requiredRole: 'sme_admin',
        priority: 'medium',
        status: 'open',
      },
      {
        id: 'admin-configure-integrations',
        title: 'Resolve integration readiness gaps',
        description: 'ERP and e-signature adapters are configured as mock/local only.',
        targetRoute: '/integrations',
        requiredRole: 'sme_admin',
        priority: 'high',
        status: 'pending_external',
      },
      {
        id: 'admin-review-audit',
        title: 'Review access-related audit events',
        description: 'Confirm recent role and membership activity.',
        targetRoute: '/audit/search',
        requiredRole: 'sme_admin',
        priority: 'low',
        status: 'open',
      },
    ],
    signals: [...sharedSignals],
    activities: [...sharedActivities],
  },
  procurement_officer: {
    role: 'procurement_officer',
    title: 'Procurement cockpit',
    subtitle:
      'Source-to-pay tasks, evidence gaps, supplier work, and requisition progress.',
    kpis: [
      {
        id: 'open-requisitions',
        label: 'Open requisitions',
        value: 7,
        helper: '2 are awaiting approval',
        trend: 'up',
        severity: 'neutral',
      },
      {
        id: 'active-rfqs',
        label: 'Active RFQs',
        value: 3,
        helper: 'Quotation comparison due this week',
        severity: 'warning',
      },
      {
        id: 'evidence-readiness',
        label: 'Evidence readiness',
        value: '73%',
        helper: 'Two items block finance review',
        trend: 'up',
        severity: 'warning',
      },
      {
        id: 'invoice-matches',
        label: 'Matching exceptions',
        value: 1,
        helper: 'Quantity variance requires review',
        severity: 'danger',
      },
    ],
    tasks: [
      {
        id: 'proc-complete-evidence',
        title: 'Complete procurement evidence for APP-2026-001',
        description: 'Due diligence is blocked until quotation and receipt evidence are linked.',
        targetRoute: '/evidence/items',
        requiredRole: 'procurement_officer',
        priority: 'high',
        status: 'blocked',
      },
      {
        id: 'proc-review-rfq',
        title: 'Compare RFQ quotations',
        description: 'Supplier responses are ready for evaluation.',
        targetRoute: '/procurement/quotations/compare',
        requiredRole: 'procurement_officer',
        priority: 'medium',
        status: 'open',
      },
      {
        id: 'proc-match-invoice',
        title: 'Resolve receipt and invoice mismatch',
        description: 'A supplier invoice does not match recorded receipt quantity.',
        targetRoute: '/procurement/matching',
        requiredRole: 'procurement_officer',
        priority: 'high',
        status: 'open',
      },
    ],
    signals: [...sharedSignals],
    activities: [...sharedActivities],
  },
  approver: {
    role: 'approver',
    title: 'Approval cockpit',
    subtitle: 'Requisition decisions, approval matrix work, and blocked procurement tasks.',
    kpis: [
      {
        id: 'pending-approvals',
        label: 'Pending approvals',
        value: 4,
        helper: 'One high-priority requisition',
        severity: 'warning',
      },
      {
        id: 'avg-decision-time',
        label: 'Average decision time',
        value: '1.4d',
        helper: 'Within current SLA',
        trend: 'down',
        severity: 'success',
      },
      {
        id: 'blocked-pos',
        label: 'Blocked purchase orders',
        value: 2,
        helper: 'Approval required before sourcing',
        severity: 'warning',
      },
      {
        id: 'policy-rules',
        label: 'Rule matches',
        value: 9,
        helper: 'Current matrix routes are active',
        severity: 'neutral',
      },
    ],
    tasks: [
      {
        id: 'approve-requisition',
        title: 'Approve submitted requisition',
        description: 'Budget and risk summary are ready for review.',
        targetRoute: '/procurement/approvals',
        requiredRole: 'approver',
        priority: 'high',
        status: 'open',
      },
      {
        id: 'review-approval-rule',
        title: 'Check approval rule result',
        description: 'Amount threshold changed after project update.',
        targetRoute: '/procurement/approval-rules',
        requiredRole: 'approver',
        priority: 'medium',
        status: 'open',
      },
    ],
    signals: [sharedSignals[2]],
    activities: [...sharedActivities],
  },
  supplier: {
    role: 'supplier',
    title: 'Supplier workspace',
    subtitle:
      'Supplier portal tasks are planned; current dashboard explains pending RFQ and evidence work.',
    kpis: [
      {
        id: 'rfq-invitations',
        label: 'RFQ invitations',
        value: 2,
        helper: 'Supplier portal route is planned',
        severity: 'warning',
      },
      {
        id: 'delivery-evidence',
        label: 'Delivery evidence',
        value: 1,
        helper: 'One upload is pending internal review',
        severity: 'neutral',
      },
      {
        id: 'invoice-status',
        label: 'Invoice status',
        value: 'Pending',
        helper: 'Internal finance matching in progress',
        severity: 'warning',
      },
      {
        id: 'shared-audit',
        label: 'Shared audit scope',
        value: 'Limited',
        helper: 'Only supplier-scoped events should be visible',
        severity: 'neutral',
      },
    ],
    tasks: [
      {
        id: 'supplier-portal-planned',
        title: 'Supplier RFQ portal is not implemented yet',
        description:
          'Use this dashboard as the current placeholder until supplier-scoped routes are added.',
        targetRoute: '/dashboard',
        requiredRole: 'supplier',
        priority: 'medium',
        status: 'blocked',
      },
    ],
    signals: [],
    activities: [],
  },
  finance: {
    role: 'finance',
    title: 'Finance and accounting cockpit',
    subtitle: 'Ledger evidence, cost/revenue reconciliation, and profit/loss readiness.',
    kpis: [
      {
        id: 'active-ledgers',
        label: 'Active ledgers',
        value: 5,
        helper: 'Two need updated entries',
        severity: 'warning',
      },
      {
        id: 'unreconciled',
        label: 'Unreconciled items',
        value: 3,
        helper: 'ERP sync or manual reconciliation required',
        severity: 'danger',
      },
      {
        id: 'pl-ready',
        label: 'P/L statements ready',
        value: 2,
        helper: 'Distribution review can begin',
        severity: 'success',
      },
      {
        id: 'allowed-costs',
        label: 'Allowed cost evidence',
        value: '86%',
        helper: 'One supplier invoice still pending',
        trend: 'up',
        severity: 'warning',
      },
    ],
    tasks: [
      {
        id: 'finance-ledger-entry',
        title: 'Record project ledger evidence',
        description: 'Revenue collection evidence has been received.',
        targetRoute: '/finance/ledgers',
        requiredRole: 'finance',
        priority: 'high',
        status: 'open',
      },
      {
        id: 'finance-profit-loss',
        title: 'Prepare preliminary profit/loss statement',
        description: 'Use approved ratio only; do not calculate guaranteed fixed return.',
        targetRoute: '/finance/profit-loss',
        requiredRole: 'finance',
        priority: 'high',
        status: 'open',
      },
    ],
    signals: [sharedSignals[1], sharedSignals[2]],
    activities: [...sharedActivities],
  },
  financier: {
    role: 'financier',
    title: 'Financier review cockpit',
    subtitle: 'Applications, due diligence queues, exposure, and monitored milestones.',
    kpis: [
      {
        id: 'pipeline',
        label: 'Application pipeline',
        value: 12,
        helper: '3 awaiting due diligence',
        trend: 'up',
        severity: 'warning',
      },
      {
        id: 'exposure',
        label: 'Current exposure',
        value: 'MYR 1.8M',
        helper: 'Across 5 monitored contracts',
        trend: 'up',
        severity: 'neutral',
      },
      {
        id: 'milestone-risk',
        label: 'At-risk milestones',
        value: 2,
        helper: 'Delivery evidence is late',
        severity: 'danger',
      },
      {
        id: 'review-cycle',
        label: 'Average review cycle',
        value: '3.2d',
        helper: 'Due diligence cycle time',
        trend: 'down',
        severity: 'success',
      },
    ],
    tasks: [
      {
        id: 'financier-dd',
        title: 'Review due diligence for APP-2026-001',
        description: 'Evidence is incomplete; request gaps before approval.',
        targetRoute: '/finance/applications',
        requiredRole: 'financier',
        priority: 'critical',
        status: 'blocked',
      },
      {
        id: 'financier-contract',
        title: 'Generate contract only after approvals exist',
        description: 'Application is not ready until financier and Shariah decisions are approved.',
        targetRoute: '/finance/contracts',
        requiredRole: 'financier',
        priority: 'high',
        status: 'blocked',
      },
      {
        id: 'financier-evidence-pack',
        title: 'Review scoped evidence pack',
        description: 'Use evidence pack before approving capital application.',
        targetRoute: '/evidence/packs',
        requiredRole: 'financier',
        priority: 'medium',
        status: 'open',
      },
    ],
    signals: [...sharedSignals],
    activities: [...sharedActivities],
  },
  shariah_reviewer: {
    role: 'shariah_reviewer',
    title: 'Shariah review cockpit',
    subtitle:
      'Eligibility, contract terms, profit ratio, loss treatment, and compliance decisions.',
    kpis: [
      {
        id: 'pending-shariah',
        label: 'Pending reviews',
        value: 3,
        helper: 'One urgent eligibility review',
        severity: 'warning',
      },
      {
        id: 'contract-terms',
        label: 'Contract terms queued',
        value: 2,
        helper: 'Profit ratio and loss treatment need review',
        severity: 'warning',
      },
      {
        id: 'guaranteed-return-risk',
        label: 'Return-risk flags',
        value: 1,
        helper: 'Check for fixed-return wording',
        severity: 'danger',
      },
      {
        id: 'approved-month',
        label: 'Approved this month',
        value: 8,
        helper: 'All with explicit review decisions',
        severity: 'success',
      },
    ],
    tasks: [
      {
        id: 'shariah-review-app',
        title: 'Record Shariah decision for APP-2026-001',
        description: 'Eligibility and profit ratio evidence are ready for review.',
        targetRoute: '/finance/applications',
        requiredRole: 'shariah_reviewer',
        priority: 'high',
        status: 'open',
      },
      {
        id: 'shariah-contract-terms',
        title: 'Review restricted contract terms',
        description: 'Confirm no guaranteed fixed return and allowed expenses are explicit.',
        targetRoute: '/finance/contracts',
        requiredRole: 'shariah_reviewer',
        priority: 'high',
        status: 'open',
      },
    ],
    signals: [sharedSignals[2]],
    activities: [...sharedActivities],
  },
  auditor: {
    role: 'auditor',
    title: 'Audit and verification cockpit',
    subtitle: 'Evidence packs, hash verification, audit search, and anchor status.',
    kpis: [
      {
        id: 'events-to-verify',
        label: 'Events to verify',
        value: 18,
        helper: 'Hash verification queue',
        severity: 'warning',
      },
      {
        id: 'pending-anchors',
        label: 'Pending anchors',
        value: 3,
        helper: 'No success shown until transaction reference exists',
        severity: 'warning',
      },
      {
        id: 'open-findings',
        label: 'Open findings',
        value: 2,
        helper: '0 critical issues',
        severity: 'neutral',
      },
      {
        id: 'packs-ready',
        label: 'Evidence packs',
        value: 7,
        helper: '2 requested for review',
        severity: 'success',
      },
    ],
    tasks: [
      {
        id: 'auditor-hash',
        title: 'Verify document hash record',
        description: 'Confirm local canonical hash before relying on anchor status.',
        targetRoute: '/evidence/hashes',
        requiredRole: 'auditor',
        priority: 'high',
        status: 'open',
      },
      {
        id: 'auditor-anchor-pending',
        title: 'Review pending Fabric anchor queue',
        description: 'Anchor requests are pending; do not mark them as verified.',
        targetRoute: '/integrations',
        requiredRole: 'auditor',
        priority: 'medium',
        status: 'pending_external',
      },
      {
        id: 'auditor-closure-pack',
        title: 'Inspect closure pack evidence',
        description: 'Review procurement evidence and audit events before export.',
        targetRoute: '/finance/closures',
        requiredRole: 'auditor',
        priority: 'medium',
        status: 'open',
      },
    ],
    signals: [...sharedSignals],
    activities: [...sharedActivities],
  },
  developer: {
    role: 'developer',
    title: 'Developer and integration cockpit',
    subtitle: 'Adapter status, outbox retries, deployment readiness, and diagnostics.',
    kpis: [
      {
        id: 'outbox-pending',
        label: 'Pending outbox',
        value: 6,
        helper: 'Worker should process these asynchronously',
        severity: 'warning',
      },
      {
        id: 'failed-integrations',
        label: 'Failed integrations',
        value: 2,
        helper: 'Manual reconciliation needed',
        severity: 'danger',
      },
      {
        id: 'node-health',
        label: 'Node health',
        value: 'Degraded',
        helper: 'Object storage health is not yet checked',
        severity: 'warning',
      },
      {
        id: 'backup-freshness',
        label: 'Backup freshness',
        value: 'Unknown',
        helper: 'Backup endpoint is planned',
        severity: 'warning',
      },
    ],
    tasks: [
      {
        id: 'dev-outbox',
        title: 'Inspect failed outbox events',
        description: 'Retries must stay visible and idempotent.',
        targetRoute: '/integrations',
        requiredRole: 'developer',
        priority: 'critical',
        status: 'open',
      },
      {
        id: 'dev-ops-planned',
        title: 'Operations readiness screen is planned',
        description: 'Use dashboard health until operations endpoints are implemented.',
        targetRoute: '/dashboard',
        requiredRole: 'developer',
        priority: 'medium',
        status: 'blocked',
      },
    ],
    signals: [...sharedSignals],
    activities: [...sharedActivities],
  },
}
